### PR TITLE
CSS changes

### PR DESCRIPTION
**Pull request by rahulkapoor90**
Added custom CSS for student login.

### CODE REVIEW

**Comment by rahulkapoor90** [comment]
Done.

**Comment by karthikb351** [comment]
I'm at work, I'll be able to test this out only in the night.

Meanwhile test it yourself like this - https://developer.chrome.com/extensions/getstarted#unpacked

Also, what kind of changes are you making via CSS?

**Comment by rahulkapoor90** [comment]
I am improving the login page of student login the input text and password boxes looks nice with the extension and button has a new UI.
Also, the font of the student login is also changed as it uses 'comic sans'.
more UI changes, can be added. Any suggestions?

**Comment by rahulkapoor90** [comment]
I'll test it now :+1:

**Comment by rahulkapoor90** [comment]
I have added another small css code to remove captcha from being show as it's automatically being filled.

**Comment by rahulkapoor90** [comment]
I just tested it and is working fine but the buttons are not displaying correctly in chrome. i need to fix that.

**Pull request closed without merging**
